export default [
  {
    id: 1,
    firstname: "Ramon",
    lastname: "Tanko",

    level: 100,
    course: "Accounting",
    department: "Finance",
    school: "Management Studies",
    status: 0,
    regNo: "233333",
    state: "Abuja",
    lga: "Bwari",
    _userId: 1,
    _createdDate: "03/31/2015",
    _updatedDate: "05/08/2015",
  },
  {
    id: 2,
    firstname: "Chidi",
    lastname: "Okoro",

    level: 100,
    course: "Computer Science",
    department: "Mathematics",
    school: "Sciences",
    state: "Abuja",
    lga: "Kuje",
    status: 0,
    regNo: "233334",
    _userId: 1,
    _createdDate: "11/11/2016",
    _updatedDate: "09/01/2016",
  },
];
